support:
    resource: "@SupportBundle/Controller/"
    type:     annotation
    prefix:   /

show:
    resource: "@ShowBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
